shared_controller_node:
  ros__parameters:
    controller_frequency: 40.          #in second. Amount of time needed to complete one cycle of vel calculation
    joystick_noise: false
    max_linear_vel: 0.3      # max linear velocity in x direction (0.3-1.6)(m/s) 
    min_linear_vel: -0.3      # min linear velocity. 
                               # Can be negative in case of backward movement . (-0.3 - -0.8)(m/s)
                               # (Maximum backward vel)
    max_yaw_rate: 0.7          # Maximum yaw rate in both clockwise and counter clockwise direction. Can only be positive. Min yaw rate = 0 (rad/s)
    max_acceleration: 1.2       # max acceleration in both direction (forward backward) ( 0.28  - 1.38m/ss)
    max_decceleration: 1.2    # max decceleration in both direction (forward backward) (1.2 - 2.5m/ss)
    max_yaw_acceleration: 2.5  # maximum yaw rate acceleration in both clockwise and counter clockwise (rad/ss)


    shared_mppi_controller:
      time_steps: 60
      model_dt: 0.1
      batch_size: 10
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.2
      vx_max: 0.3
      vx_min: -0.3
      vy_max: 0.
      wz_max: 0.7
      ax_max: 1.2  
      ax_min: -1.2
      ay_max: 0.
      az_max: 2.5 
      iteration_count: 1
      prune_distance: 1.7
      temperature: 0.4
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: true
      reset_period: 1.0 # (only in Humble)
      retry_attempt_limit: 3
      regenerate_noises: false
      TrajectoryVisualizer:
        trajectory_step: 1000
        time_step: 3
      critics: ["ConstraintCritic", "GoalCritic", "GoalAngleCritic", "PreferForwardCritic", "UserSpeedCritic", "LidarObstaclesCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.0
        threshold_to_consider: 5.0
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.0
        threshold_to_consider: 5.0
      PreferForwardCritic:
        enabled: false
        cost_power: 1
        cost_weight: 1.0
        threshold_to_consider: 0.5
      UserSpeedCritic:
        enable: false
        cost_power: 1
        cost_weight: 1.0
        decay_rate: 0.0
      LidarObstaclesCritic:
        enabled: true
        cost_power: 1.0
        weight: 1.0
        footprint_frame: "base_footprint"
        footprint_length: 1.0
        footprint_width: 0.6
        scan_topic: "/scan" 
        collision_costt: 1000000



