shared_controller_node:
  ros__parameters:
    controller_frequency: 10.          #in second. Amount of time needed to complete one cycle of vel calculation
    joystick_noise: true
    noise_freq : 5.0
    noise_std: 0.4
    max_linear_vel: 0.3      # max linear velocity in x direction (0.3-1.6)(m/s) 
    min_linear_vel: -0.3      # min linear velocity. 
                               # Can be negative in case of backward movement . (-0.3 - -0.8)(m/s)
                               # (Maximum backward vel)
    max_yaw_rate: 0.7          # Maximum yaw rate in both clockwise and counter clockwise direction. Can only be positive. Min yaw rate = 0 (rad/s)
    max_acceleration: 1.2       # max acceleration in both direction (forward backward) ( 0.28  - 1.38m/ss)
    max_decceleration: 1.2    # max decceleration in both direction (forward backward) (1.2 - 2.5m/ss)
    max_yaw_acceleration: 2.5  # maximum yaw rate acceleration in both clockwise and counter clockwise (rad/ss)


    shared_mppi_controller:
      time_steps: 40
      model_dt: 0.1
      batch_size: 2500
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.3
      vx_max: 0.3
      vx_min: -0.3
      vy_max: 0.
      wz_max: 0.7
      ax_max: 1.2  
      ax_min: -1.2
      ay_max: 0.
      az_max: 2.5 
      iteration_count: 1
      prune_distance: 1.7
      temperature: 0.3
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: true
      reset_period: 1.0 # (only in Humble)
      retry_attempt_limit: 3
      regenerate_noises: false
      TrajectoryVisualizer:
        trajectory_step: 100
        time_step: 2
      critics: ["ConstraintCritic", "GoalCritic", "GoalAngleCritic", "UserSpeedCritic", "LidarObstaclesCritic", "SmoothVelocityCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
        threshold_to_consider: 4.0
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 0.5
        threshold_to_consider: 4.0
        confidence_factor: 5
      UserSpeedCritic:
        enable: true
        cost_power: 2
        cost_weight: 4.0
        decay_rate: 0.0
        linear_speed_weight: 2.0 
        angular_speed_weight: 0.8
      LidarObstaclesCritic:
        enabled: true
        cost_power: 1.0
        weight: 1.0
        footprint_frame: "base_footprint"
        footprint_length: 0.85
        footprint_width: 0.62
        scan_topic: "/scan" 
        collision_cost: 1000000000.0
        collision_considered_range: 2.0
        repulsion_considered_range: 0.1
        cost_reduction_factor : 10
      SmoothVelocityCritic:
        enable: true
        power: 1
        weight: 4.0
        linear_speed_weight: 1.0
        angular_speed_weight: 1.0

