share_control_node:
  ros__parameters:
    predict_time:  1.0    #double
    predict_timestep: 0.1     #double
    scan_to_obstacle_range: 2. #double 
    skip_point:  2             #int
    period: 0.1               #in second. Amount of time needed to complete one cycle of vel calculation
    linear_velocity_sample_size: 7
    yaw_rate_sample_size: 20
    joystick_noise: false
    noise_freq : 5.0
    noise_std: 0.4
    max_linear_vel: 0.3      # max linear velocity in x direction (0.3-1.6)(m/s) 
    min_linear_vel: -0.3      # min linear velocity. 
                               # Can be negative in case of backward movement . (-0.3 - -0.8)(m/s)
                               # (Maximum backward vel)
    max_yaw_rate: 0.7          # Maximum yaw rate in both clockwise and counter clockwise direction. Can only be positive. Min yaw rate = 0 (rad/s)
    max_acceleration: 1.2       # max acceleration in both direction (forward backward) ( 0.28  - 1.38m/ss)
    max_decceleration: 1.2    # max decceleration in both direction (forward backward) (1.2 - 2.5m/ss)
    max_yaw_acceleration: 2.5  # maximum yaw rate acceleration in both clockwise and counter clockwise (rad/ss)
    rectangle_footprint:  # Specify detail about rectangular footprint
      use: true 
      height: 0.85
      width: 0.6
    footprint_radius: 0.4 # In case do not use rectangular footprint, circular footprint is used by default. This parameter regulate the radius 
                          # of circular footprint       
    user_weight : 2.0
    linear_speed_weight : 1.0
    angular_speed_weight : 1.0

    obstacle_weight : 0.0
    repulsion_considered_range: 0.1
    cost_reduction_factor: 10.0