planner_server:
  ros__parameters:
    expected_planner_frequency: 60.0
    costmap_update_timeout: 0.2
    service_introspection_mode: "disabled"
    planner_plugins: ['GridBased']
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner'
      tolerance: 0.25


global_costmap/global_costmap:
  ros__parameters: 
    update_frequency: 20.0
    publish_frequency: 20.0
    footprint: "[[0.75, 0.31],[0.75,-0.31],[-0.2,-0.31],[-0.2,0.31]]"  # Robot footprint
    global_frame: base_footprint
    robot_base_frame: base_link
    use_sim_time: False
    rolling_window: True  # Enable rolling window for the local costmap
    width: 6  # Size of the local costmap (around the robot)
    height: 6
    resolution: 0.03
    plugins: ["obstacle_layer", "inflation_layer"]  # Add desired layers
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      footprint_clearing_enabled: false
      observation_sources: scan  # Subscribe to scan data
      max_obstacle_height: 2.0
      combination_method: 0
      scan:
        topic: /scan
        sensor_frame: base_footprint
        obstacle_max_range: 3.0
        obstacle_min_range: 0.0
        raytrace_max_range: 3.0
        raytrace_min_range: 0.0
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        clearing: true
        marking: true
        data_type: "LaserScan"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 1.0
      cost_scaling_factor: 5.0
      inflate_unknown: false
      inflate_around_unknown: true

